Repository kusitms32th-zighang-2/ZIGHANG_ENTERPRISE_PROJECT_BE, pull requests merged in 2025-09, with the labels that each got.

#18 feature: 마이페이지 조회 API (#17)
  src/main/java/zighang2/zighang/web/controller/UserController.java
  src/main/java/zighang2/zighang/web/dto/UserDto.java
  src/main/java/zighang2/zighang/web/service/UserService.java
Labels: ✨ feature

#21 Feat/onboarding page
  src/main/java/zighang2/zighang/global/payload/code/status/ErrorStatus.java
  src/main/java/zighang2/zighang/web/controller/OnboardingController.java
  src/main/java/zighang2/zighang/web/controller/UserController.java
  src/main/java/zighang2/zighang/web/converter/AuthConverter.java
  src/main/java/zighang2/zighang/web/domain/enums/JobGroup.java
  src/main/java/zighang2/zighang/web/domain/enums/JobPosition.java
  src/main/java/zighang2/zighang/web/domain/enums/Transport.java
  src/main/java/zighang2/zighang/web/domain/enums/UserRole.java
  src/main/java/zighang2/zighang/web/domain/user/OnboardingCharacter.java
  src/main/java/zighang2/zighang/web/domain/user/User.java
  src/main/java/zighang2/zighang/web/dto/OnboardingDto.java
  src/main/java/zighang2/zighang/web/dto/UserDto.java
  src/main/java/zighang2/zighang/web/repository/OnboardingRepository.java
  src/main/java/zighang2/zighang/web/service/AuthService.java
  src/main/java/zighang2/zighang/web/service/OnboardingService.java
  src/main/resources/.gitkeep
Labels: ✨ feature

#22 [Feat] 통근 시간 필터링 구현 & 추천 공고 6개 조회 API (#19)
  build.gradle
  src/main/java/zighang2/zighang/global/auth/jwt/JwtProvider.java
  src/main/java/zighang2/zighang/global/auth/jwt/KakaoUtil.java
  src/main/java/zighang2/zighang/global/config/RedisConfig.java
  src/main/java/zighang2/zighang/global/config/TmapClient.java
  src/main/java/zighang2/zighang/global/config/WebClientConfig.java
  src/main/java/zighang2/zighang/global/payload/code/status/ErrorStatus.java
  src/main/java/zighang2/zighang/global/utils/TimeFormatter.java
  src/main/java/zighang2/zighang/web/controller/AuthController.java
  src/main/java/zighang2/zighang/web/controller/OnboardingController.java
  src/main/java/zighang2/zighang/web/controller/RecommendController.java
  src/main/java/zighang2/zighang/web/converter/AuthConverter.java
  src/main/java/zighang2/zighang/web/domain/JobRecommend.java
  src/main/java/zighang2/zighang/web/domain/enums/CompanyType.java
  src/main/java/zighang2/zighang/web/domain/enums/Education.java
  src/main/java/zighang2/zighang/web/domain/enums/JobGroup.java
  src/main/java/zighang2/zighang/web/domain/enums/JobPosition.java
  src/main/java/zighang2/zighang/web/domain/enums/RecruitmentType.java
  src/main/java/zighang2/zighang/web/domain/user/OnboardingCharacter.java
  src/main/java/zighang2/zighang/web/domain/user/User.java
  src/main/java/zighang2/zighang/web/dto/JobRecommendDto.java
  src/main/java/zighang2/zighang/web/dto/UserDto.java
  src/main/java/zighang2/zighang/web/dto/kakaoLogin/KakaoDto.java
  src/main/java/zighang2/zighang/web/dto/kakaoLogin/TokenResponseDto.java
  src/main/java/zighang2/zighang/web/dto/tmap/GeocodePoint.java
  src/main/java/zighang2/zighang/web/dto/tmap/response/TmapGeocodingResponseDto.java
  src/main/java/zighang2/zighang/web/dto/tmap/response/TmapResponseDto.java
  src/main/java/zighang2/zighang/web/repository/JobRecommendRepository.java
  src/main/java/zighang2/zighang/web/service/AuthService.java
  src/main/java/zighang2/zighang/web/service/RecommendService.java
Labels: ✨ feature

#24 [Feat] 마이프로필 정보 수정 API & 조회 API에 필드 추가 (#14 & #17)
  src/main/java/zighang2/zighang/web/domain/enums/CompanyType.java
  src/main/java/zighang2/zighang/web/domain/enums/Education.java
  src/main/java/zighang2/zighang/web/domain/enums/JobGroup.java
  src/main/java/zighang2/zighang/web/domain/enums/JobPosition.java
  src/main/java/zighang2/zighang/web/domain/enums/RecruitmentType.java
  src/main/java/zighang2/zighang/web/domain/user/User.java
  src/main/java/zighang2/zighang/web/dto/UserDto.java
  src/main/java/zighang2/zighang/web/service/UserService.java
Labels: ✨ feature

#41 Feat/work experience field modi
  src/main/java/zighang2/zighang/global/service/RedisService.java
  src/main/java/zighang2/zighang/global/utils/WorkExperienceFormatter.java
  src/main/java/zighang2/zighang/web/controller/HealthCheckController.java
  src/main/java/zighang2/zighang/web/controller/UserController.java
  src/main/java/zighang2/zighang/web/domain/JobRecommend.java
  src/main/java/zighang2/zighang/web/dto/JobPostingResponseDto.java
  src/main/java/zighang2/zighang/web/dto/OnboardingDto.java
  src/main/java/zighang2/zighang/web/dto/SearchDto.java
  src/main/java/zighang2/zighang/web/dto/UserDto.java
  src/main/java/zighang2/zighang/web/repository/JobRecommendRepository.java
  src/main/java/zighang2/zighang/web/service/OnboardingService.java
  src/main/java/zighang2/zighang/web/service/RecommendService.java
  src/main/java/zighang2/zighang/web/service/SearchService.java
  src/main/java/zighang2/zighang/web/service/UserService.java
Labels: ✨ feature, ♻️ refactor

#42 Feat/work experience field modi
  src/main/java/zighang2/zighang/web/dto/UserDto.java
  src/main/java/zighang2/zighang/web/service/UserService.java
Labels: 🐛 fix, ✨ feature

#45 feat : 마이페이지 테스트 다시하기 구현(#44)
  src/main/java/zighang2/zighang/web/controller/UserController.java
  src/main/java/zighang2/zighang/web/domain/JobPosition.java
  src/main/java/zighang2/zighang/web/domain/user/User.java
  src/main/java/zighang2/zighang/web/dto/OnboardingDto.java
  src/main/java/zighang2/zighang/web/dto/UserDto.java
  src/main/java/zighang2/zighang/web/repository/JobRecommendRepository.java
  src/main/java/zighang2/zighang/web/repository/UserCompanyTypeRepository.java
  src/main/java/zighang2/zighang/web/repository/UserJobPositionRepository.java
  src/main/java/zighang2/zighang/web/service/UserService.java
Labels: ✨ feature

#56 feat : user delete (#55)
  src/main/java/zighang2/zighang/web/controller/UserController.java
  src/main/java/zighang2/zighang/web/service/UserService.java
Labels: ✨ feature

#59 57/refactor charcter enum
  src/main/java/zighang2/zighang/web/service/RecommendService.java
Labels: ✨ feature
